server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: logger
        uri: lb://logger
        predicates:
          - Path=/logger/**
      - id: accounting
        uri: lb://accounting
        predicates:
          - Path=/accounting/**



