spring:
  application:
    name: pepper
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 9011

eureka:
  instance:
    hostname: pepper
  client:
    serviceUrl:
      defaultZone: http://discovery:9010/eureka/


