spring:
  application:
    name: accounting
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 9001
  connection-timeout: 15000

eureka:
  instance:
    hostname: accounting
  client:
    serviceUrl:
      defaultZone: http://discovery:9010/eureka/



