spring:
  application:
    name: accounting
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres/task
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/



